version: "3.9"

services:
  db:
    container_name: apicaffe
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "${USER_DB}"
      POSTGRES_PASSWORD: "${PASS_DB}"
      POSTGRES_DB: "${NAME_DB}"
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
